Insight without export options
2pisoftware/cmfive-core pull request #102
Opened 2021-02-23 01:11 UTC by Tinystep1

## Checklist
- [X] I'm using the correct PHP Version (7.2 for current, 7.0 for legacy).
- [X] Tests are passing.
- [X] I've added comments to any new methods I've created or where else relevant.
- [X] PHPCS has reported no errors to my changes.
- [X] I've replaced magic method usage on DbService classes with the getInstance() static method.

Insights module with option to change preferences once run. No export options

- replaced core report functionality with class based implementation

refs: 9930

2021-02-23 22:59 UTC, adam-buckley requested changes
Hi Alice, I think the roles comment is the most important issue out of them all. If you need a hand implementing this let me know. Roles can be weird

2021-02-23 22:59 UTC, adam-buckley commented on system/modules/insights/actions/export/csv.php
> +    $run_data = $insight->run($w, $_REQUEST);
We should be checking here that an insight was found, if there is no insight found with the class name then a php fatal error will be thrown

2021-02-23 22:59 UTC, adam-buckley commented on system/modules/insights/actions/index.php
> +  LogService::getInstance($w)->setLogger("INSIGHTS")->info("This is an INSIGHTS.INFO message");
While we're making changes please remove these log messages as they may clog up a production systems logs

2021-02-23 22:59 UTC, adam-buckley commented on system/modules/insights/actions/members/editMembers.php
> +		$postUrl = '/insights-members/editMembers';
This whole if/else statement could be condensed into ```$postUrl = '/insights-members/editMembers/' . (!empty($member->id) ? $member->id : '');```

2021-02-23 22:59 UTC, adam-buckley commented on system/modules/insights/insights.roles.php
> +    return $w->checkUrl($path, "insights", "*", "*");
This insights_user role will allow users who have this role to manage membership to an insight, my assumption is that this should be reserved only for insights_admin

2021-02-23 22:59 UTC, adam-buckley commented on system/modules/insights/models/InsightService.php
> +            return null;
One nice side effect of getObject is that if the record isn't found in the database, null is returned. Ideally this function should return the whole ```$insight_member``` object and not the type and let the invoking function extract the type or any other property it needs.

Since this works, for now I wouldn't bother changing this but perhaps note it as something to do in a future update

2021-02-23 22:59 UTC, adam-buckley commented on system/modules/insights/models/InsightService.php
> +        if ($date) {
This isn't needed, the ```formatDate``` and ```formatDateTime``` functions in system/functions.php takes care of this

2021-03-02 01:21 UTC, Tinystep1 commented on system/modules/insights/insights.roles.php
> +    return $w->checkUrl($path, "insights", "*", "*");
An owner of an insight is also allowed to manage members for that insight, but not all owners are admins.

2021-03-02 01:22 UTC, Tinystep1 commented on system/modules/insights/insights.roles.php
> +    return $w->checkUrl($path, "insights", "*", "*");
You can actually see this when the index checks if the insight member is an admin or owner before showing the manage members button

2021-03-02 01:58 UTC, Tinystep1 commented on system/modules/insights/actions/export/csv.php
> +    $run_data = $insight->run($w, $_REQUEST);
added checks. Fatal errors not thrown

2021-03-02 01:59 UTC, Tinystep1 commented on system/modules/insights/actions/index.php
> +  LogService::getInstance($w)->setLogger("INSIGHTS")->info("This is an INSIGHTS.INFO message");
removed

2021-03-02 02:16 UTC, Tinystep1 commented on system/modules/insights/models/InsightService.php
> +        if ($date) {
Done

2021-03-02 23:10 UTC, Tinystep1 commented on system/modules/insights/actions/members/editMembers.php
> +		$postUrl = '/insights-members/editMembers';
Done

2021-03-02 23:14 UTC, Tinystep1 commented
Hi Adam. Ready for review again

2021-03-11 23:27 UTC, merged