fix: send attachments without cache or memory
2pisoftware/cmfive-core pull request #113
Opened 2021-03-10 02:22 UTC by DerekCrannaford

## Checklist
- [*] I'm using the correct PHP Version (7.2 for current, 7.0 for legacy).
- [-] Tests are passing -> manual tests applied for this use case!
- [*] I've added comments to any new methods I've created or where else relevant.
- [?] PHPCS has reported no errors to my changes.
- [*] I've replaced magic method usage on DbService classes with the getInstance() static method.

## Description = attachment feature/action 'atfile' cannot handle large files. Created new action 'atdownload' (renamed from 'atpull') and supporting method 'writeOut' to handle cmfive abstracted attachment/file as output to browser as PHP low level stream.

## Changelog
 - new action on attachments: atpull
 - supporting method: attachment->writeOut()
 - addition to download role, allowing 'atpull' as per 'atfile'

refs:
issues: important for correct function of cloud uploader and EMM download links

## Other Information

2021-03-10 02:40 UTC, DerekCrannaford commented on system/modules/file/models/Attachment.php
> +        $this->w->header('Content-Type: application/octet-stream');
I'm no expert, but apparently octet-stream is indicated for intention of file download, where mime-type would be a hint to browser interaction (eg: display/markup)

2021-03-10 03:00 UTC, DerekCrannaford commented on system/modules/file/models/Attachment.php
> +        $this->w->header('Content-Type: application/octet-stream');
Hmm. MDN says:
"Avoid using application/octet-stream as most browsers do not allow defining a default behavior (like "Open in Word") for this generic MIME type. A specific type like application/vnd.mspowerpoint lets users open such files automatically in the presentation software of their choice."

I'm not entirely convinced,
'atpull' is expecting to trigger a download and to ameliorate large file glitches, so is better served by 'Save-As' than 'Open-With' anyway?

2021-03-10 03:13 UTC, adam-buckley commented on system/modules/file/models/Attachment.php
> +        $this->w->header('Content-Type: application/octet-stream');
I think that the "open with" prompt is _after_ it has downloaded? Your example on zoom was using the files mime type and that worked didn't it?

2021-03-10 03:52 UTC, DerekCrannaford commented on system/modules/file/models/Attachment.php
> +        $this->w->header('Content-Type: application/octet-stream');
"after it has downloaded?" ... kind of: in Firefox = there is a pause (seems related to size) then the prompt -> then if it is big it snaps to 'downloads' progress tab -> otherwise opens straight up ... browser behaviour out of our hands really, beyond we try to send healthy headers.

Have added commit to carry through mimetype, as allowance for most general use cases and best formed headers.

2021-03-17 21:49 UTC, strongishllama requested changes
Hey @DerekCrannaford, some minor changes requested. Would be keen to get @adam-buckley's input too.

2021-03-17 21:49 UTC, strongishllama commented on system/modules/file/actions/atpull.php
> +function atpull_GET(Web &$w)
A minor thing, but to me, it makes more sense to call this action "stream_GET" or "atStream_GET".

2021-03-17 21:49 UTC, strongishllama commented on system/modules/file/models/Attachment.php
> +    public function writeOut()
Is there a use case for this functionality to be put into a method on the Attachment class so it can be used elsewhere? If not, it feels like this logic should be put into the atPull_GET action. I don't think we want to add methods to classes unless they can be reused in other places.

2021-03-17 21:49 UTC, strongishllama commented on system/modules/file/models/Attachment.php
> +        exit(0);
Even if this functionality is kept here in a method and not put into the action, do we want exit being called here? It might be something quite tricky to debug if the process is exiting all of a sudden.

2021-03-17 22:17 UTC, adam-buckley commented on system/modules/file/models/Attachment.php
> +    public function writeOut()
It should be in the FileService class so that it can be used by other modules if needed

2021-03-17 22:18 UTC, adam-buckley commented on system/modules/file/models/Attachment.php
> +        exit(0);
I think here exit is necessary to prevent more data being written to the response

2021-03-17 22:19 UTC, adam-buckley commented on system/modules/file/actions/atpull.php
> +function atpull_GET(Web &$w)
Or "download"? This is for downloading files isnt it?

2021-03-17 22:21 UTC, adam-buckley requested changes

2021-03-17 22:21 UTC, adam-buckley commented on system/modules/file/models/Attachment.php
>          $saveAs = empty($this->title) ? "File_Download" : $this->title;
This should actually be using the "filename" property so that it includes the extension

2021-03-17 22:25 UTC, adam-buckley commented on system/modules/file/models/Attachment.php
>          $saveAs = empty($this->title) ? "File_Download" : $this->title;
I'd also like to see no single use variables. For e.g:
```php
        $mime = empty($this->mimetype) ? "application/octet-stream" : $this->mimetype;
        $this->w->header('Content-Type: ' . $mime);
```
could easily be
```php
        $this->w->header('Content-Type: ' . ($this->mimetype ?? "application/octet-stream"));
```
or if you need to check for empty string (I think)
```php
        $this->w->header('Content-Type: ' . ($this->mimetype ? : "application/octet-stream"));
```

2021-03-18 00:14 UTC, DerekCrannaford commented on system/modules/file/actions/atpull.php
> +function atpull_GET(Web &$w)
I'll go with 'atdownload' (which is typical response by browser), as it pairs with 'atfile' (which generally will open as view in browser)

2021-03-18 00:20 UTC, DerekCrannaford commented on system/modules/file/models/Attachment.php
> +    public function writeOut()
It does need filesystem/filename&mimetype all as inputs, which intelligently should be coming from an attachment object.
(we don't have a very meaningful model for 'files' otherwise?)
So, I will make:
writeOutAttachment by $id in FileService
with $this->writeOut as a wrapper in Attachment class

2021-03-18 00:24 UTC, DerekCrannaford commented on system/modules/file/models/Attachment.php
> +        exit(0);
Yes - this should always exit, it could make a mess if headers&output try to hitch a ride on the end.

2021-03-18 04:20 UTC, adam-buckley approved these changes

2021-03-18 04:35 UTC, strongishllama submitted a review, later dismissed

2021-03-18 22:45 UTC, strongishllama requested changes

2021-03-18 22:45 UTC, strongishllama commented on system/modules/file/models/Attachment.php
> +    public function writeOut($saveAs = null)
@DerekCrannaford could please add type hinting to the parameters? It should be something like
```public function writeOut(?string $sageAs = null): void```

2021-03-18 22:45 UTC, strongishllama commented on system/modules/file/models/Attachment.php
> +     * @return exit(0) Terminates execution!
@DerekCrannaford this line should be ```* @return void``` and the terminates execution message put in the main part of the comment. This might seem pedantic but it will help in the future when we want to auto generate documentation from comments.

2021-03-18 22:45 UTC, strongishllama commented on system/modules/file/models/FileService.php
> +    public function writeOutAttachment($att, $saveAs = null)
@DerekCrannaford same deal with the type hinting here as above. It should look something like.
```public function writeOutAttachment(Attachment $attachment, ?string $saveAs = null): void```

2021-03-18 22:45 UTC, strongishllama commented on system/modules/file/models/FileService.php
> +        if (is_a($att, "Attachment")) {
@DerekCrannaford adding the type hinting mentioned above means you can remove this if check because it will always be an attachment.

2021-03-18 22:45 UTC, strongishllama commented on system/modules/file/models/FileService.php
> +     * @return exit(0) Terminates execution!
@DerekCrannaford same deal here with the return comment. ```* @return void```

2021-03-26 02:14 UTC, strongishllama approved these changes

2021-03-30 00:59 UTC, merged