Audit Insight
2pisoftware/cmfive-core pull request #122
Opened 2021-03-31 02:11 UTC by Tinystep1

## Checklist
- [X] I'm using the correct PHP Version (7.2 for current, 7.0 for legacy).
- [X] Tests are passing.
- [X] I've added comments to any new methods I've created or where else relevant.
- [X] PHPCS has reported no errors to my changes.
- [X] I've replaced magic method usage on DbService classes with the getInstance() static method.

The new Audit Insight and relevant changes to service functions

- Created AuditInsight file
- Added information from AuditReport as SQL
- Placed AuditInsight in admin folder
- Converted SQL in get_filters and run to PHP
- Added relevant service function to AuditService to get information based on parameters selected
- Added relevant service functions to AuditService so 'Change parameters' button will work
- Deleted excess comments (old code) and var_dump/dies

refs:9554

2021-03-31 02:32 UTC, adam-buckley requested changes

2021-03-31 02:32 UTC, adam-buckley commented on system/modules/admin/models/AuditService.php
> +        $results = $this->getObjects('Audit', $where);
You can also put the date filtering inside the where clause, this will speed up (significantly) running this insight on systems that have large amounts of audit data (some systems have 300,000,000+ rows). To do this, it should look something like (untested):
```
$where["dt_created >= ?"] = formatDateTime($dt_from, "Y-m-d H:i:s");
```

2021-03-31 02:32 UTC, adam-buckley commented on system/modules/admin/models/AuditService.php
> +        $results = $this->getObjects('Audit', $where);
(also, reverse the sign for the opposite end: ```$where["dt_created <= ?"] = formatDateTime($dt_to, "Y-m-d H:i:s");```)

2021-05-04 03:32 UTC, Tinystep1 commented on system/modules/admin/models/AuditService.php
> +        $results = $this->getObjects('Audit', $where);
Shouldn't this be $where["dt_created >= ?"] = getTimstamp(d/m/Y H:i:s', $dt_from . ' 00:00:00'); because dt_created is in the timestamp format?

2021-05-04 03:36 UTC, Tinystep1 commented on system/modules/admin/models/AuditService.php
> +        $results = $this->getObjects('Audit', $where);
This is the purpose of the code above the foreach which actually does the filtering.

2021-05-04 03:50 UTC, Tinystep1 commented on system/modules/admin/models/AuditService.php
> +        $results = $this->getObjects('Audit', $where);
I know the above code is incorrect, but something along those lines so that the user-selected parameters can interact with dt_created in the database.

2021-05-17 23:02 UTC, strongishllama commented
Hey @Tinystep1, just had a quick look at this and it looks like the tests aren't passing. You'll want to merge the latest changest from ```2pisoftware/develop``` into your branch and see if that gets them working. Shout out if you need help with this, merging branches from different origins can be tricky!

2021-05-17 23:05 UTC, strongishllama requested changes
Hey @Tinystep1, just had a quick look at this and it looks like the tests aren't passing. You'll want to merge the latest changes from ```2pisoftware/develop``` into your branch and see if that gets them working. Shout out if you need help with this, merging branches from different origins can be tricky!

2021-05-19 22:58 UTC, strongishllama commented
Hey @Tinystep1, it looks like this PR has the same/similar changes to [this](https://github.com/2pisoftware/cmfive-core/pull/134) one. Is this PR still needed?

2021-05-21 13:16 UTC, Tinystep1 commented
The second one (including export to CSV) was a branched from the original
PRs branch, so yeah, it would have the same changes, plus a few more. I
also merged the changes Adam requested on the first branch into the CSV one
so the Audit Insight pull request could be closed now that the change has
been made.

On Thu, May 20, 2021 at 8:59 AM Taliesin Millhouse ***@***.***>
wrote:

> Hey @Tinystep1 <https://github.com/Tinystep1>, it looks like this PR has
> the same/similar changes to this
> <https://github.com/2pisoftware/cmfive-core/pull/134> one. Is this PR
> still needed?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/2pisoftware/cmfive-core/pull/122#issuecomment-844552474>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANK3JWU3FTB5J67YOCVIYN3TOQ7EHANCNFSM42DOFMVA>
> .
>

2021-05-21 21:56 UTC, strongishllama commented
@Tinystep1 Great, if you head to the bottom of this PR you can do that by clicking the Close button.

2021-05-25 03:39 UTC, closed without merging