feat: format currency
2pisoftware/cmfive-core pull request #126
Opened 2021-04-22 03:46 UTC by strongishllama

## Checklist
- [ ] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
- [ ] I've added comments to any new methods I've created or where else relevant.
- [ ] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [ ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Changelog
- Deprecated formatMoney() function.
- Added new formatCurrency() function.
- Added unit tests for formatcurrency() function.
- Cleaned up various deprecation comments.
- Added removal version to deprecated functions/methods.

refs: 10215

2021-04-23 06:29 UTC, adam-buckley requested changes

2021-04-23 06:29 UTC, adam-buckley commented on system/classes/DbPDO.php
> -     * @see DbPDO::fetchElement()
@see serves a purpose (I think) for helping IDEs show links in the popup docs

2021-04-23 06:29 UTC, adam-buckley commented on system/functions.php
> +    return (new NumberFormatter($locale, NumberFormatter::CURRENCY))->formatCurrency($value, $currency);
Weren't we gonna add the backwards compat stuff?

2021-04-25 22:30 UTC, strongishllama commented on system/classes/DbPDO.php
> -     * @see DbPDO::fetchElement()
**@see** does render on its own line, which is nice. But it renders it down below all the **@param** and **@return** tags. So it ends up nowhere near the **@deprecated** tag. On comment blocks with lots of **@param** tags require scrolling it can be easy to miss. Either way, happy to change it back.

See screenshots for examples.
![Screenshot from 2021-04-26 08-27-50](https://user-images.githubusercontent.com/30204322/116011701-a120f280-a669-11eb-8f18-115c56ebe0f8.png)
![Screenshot from 2021-04-26 08-28-05](https://user-images.githubusercontent.com/30204322/116011702-a4b47980-a669-11eb-95de-2c215defd1e7.png)

2021-04-25 22:44 UTC, strongishllama commented on system/functions.php
> +    return (new NumberFormatter($locale, NumberFormatter::CURRENCY))->formatCurrency($value, $currency);
I thought the plan was to have the new ```formatCurrency``` method so we could take advantage of a different set of parameters and mark the old ```formatMoney``` for deprecation and removal in v5.0.0? But I may have misunderstood you. ```formatMoney``` is now [calling](https://github.com/2pisoftware/cmfive-core/blob/8fdf8a00d47ede12e7e5ddc35918f5709e67487e/system/functions.php#L549) ```formatCurrency``` as well.

2021-04-27 04:06 UTC, strongishllama commented on system/classes/DbPDO.php
> -     * @see DbPDO::fetchElement()
@adam-buckley updated the doc-block comments to have **@see** on a separate line as discussed.

2021-04-27 04:07 UTC, adam-buckley approved these changes

2021-04-27 04:19 UTC, merged