Fix: large attachment downloads
2pisoftware/cmfive-core pull request #142
Opened 2021-06-21 23:45 UTC by DerekCrannaford

Hotfix/large attachment downloads

## Checklist
- [y] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
- [y] I've added comments to any new methods I've created or where else relevant.
- [?] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [?] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description
s3 presigning as in use for large file requirements on client proof site

## Changelog

refs:
issues:

## Other Information

Docs pull request:

2021-06-30 05:55 UTC, strongishllama requested changes
@DerekCrannaford Mostly all good, just a few minor questions/changes.

2021-06-30 05:55 UTC, strongishllama commented on system/modules/file/models/FileService.php
> +        // if (Config::get("system.environment", ENVIRONMENT_PRODUCTION) === ENVIRONMENT_DEVELOPMENT) {
@DerekCrannaford Is there any reason we're not using IAM roles for production?

2021-06-30 05:55 UTC, strongishllama commented on system/modules/file/models/FileService.php
> +                // $args = [
@DerekCrannaford Would be worth removing this commented code I think.

2021-06-30 05:55 UTC, strongishllama commented on system/modules/file/models/FileService.php
> +
@DerekCrannaford Same for here as well.

2021-07-06 01:45 UTC, DerekCrannaford commented on system/modules/file/models/FileService.php
> +        // if (Config::get("system.environment", ENVIRONMENT_PRODUCTION) === ENVIRONMENT_DEVELOPMENT) {
'Back compatible' - if no IAM/host_role, key&secret from config. will be passed via SDK. (vegemite WooStore was this)
If config. is missing/null there is no error in SDK call, but IAM/host_role will automatically step in. (EMM from stack is this)
If not credentials anywhere, of course, SDK will fail!

2021-07-06 01:53 UTC, DerekCrannaford commented on system/modules/file/models/FileService.php
> +        // if (Config::get("system.environment", ENVIRONMENT_PRODUCTION) === ENVIRONMENT_DEVELOPMENT) {
(Actually, that might not be the question you were asking...)
Not entirely sure what this is:
if (Config::get("system.environment", ENVIRONMENT_PRODUCTION) === ENVIRONMENT_DEVELOPMENT) {
            $args["credentials"] = Config::get("file.adapters.s3.credentials");
        }
It isn't my logic.

2021-07-06 01:53 UTC, DerekCrannaford commented on system/modules/file/models/FileService.php
> +                // $args = [
Can do.

2021-07-06 02:04 UTC, DerekCrannaford commented on system/modules/file/models/FileService.php
> +        // if (Config::get("system.environment", ENVIRONMENT_PRODUCTION) === ENVIRONMENT_DEVELOPMENT) {
Config::get("system.environment", ENVIRONMENT_PRODUCTION) is not applied to s3 file functions under legacy 7.2
So I did not 'upgrade' it to, in case of unknow regressions. (probably none!)

2021-07-06 02:20 UTC, strongishllama commented on system/modules/file/models/FileService.php
> +        // if (Config::get("system.environment", ENVIRONMENT_PRODUCTION) === ENVIRONMENT_DEVELOPMENT) {
Ah makes sense. I think it would be good to add back in, roles in production in much more secure.

2021-07-09 01:30 UTC, DerekCrannaford commented on system/modules/file/models/FileService.php
> +        // if (Config::get("system.environment", ENVIRONMENT_PRODUCTION) === ENVIRONMENT_DEVELOPMENT) {
Comments removed to clarify non-conformance vs 7.4

2021-07-09 01:30 UTC, DerekCrannaford commented on system/modules/file/models/FileService.php
> +                // $args = [
Comments removed to clarify non-conformance vs 7.4

2021-07-09 01:30 UTC, DerekCrannaford commented on system/modules/file/models/FileService.php
> +
Comments removed to clarify non-conformance vs 7.4

2021-07-09 04:25 UTC, strongishllama approved these changes

2021-07-09 04:28 UTC, merged