feature/InsightTemplates
2pisoftware/cmfive-core pull request #151
Opened 2021-08-17 01:07 UTC by Tinystep1

## Checklist
- [X] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
- [X] I've added comments to any new methods I've created or where else relevant.
- [X] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [X] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

Added ability to export insights in PDF format using a template

 - Created Export to PDF button
 - Module pops-up when button clicked
 - Template list will only display templates created for specific insight PDF Exports
 - Module closes when clicked outside of
 - Module closes when X or close is clicked
- Module closes after Save is selected

refs: 10244

## Other Information

Docs pull request:

2021-08-17 02:24 UTC, strongishllama requested changes
@Tinystep1 Nice work on the export. I did have a couple of thoughts/questions.

- Getting a deprecated message on ```array_key_exists()```. I believe there was another PR that was attempting to deal with this, what's the status on that?
- Export to PDF has a field for selecting a template with no options but the export still works. Is this expected?
- The title of the pull request should be changed to ```feat: insight templates``` to comply with the semantic pull requests action.

2021-08-17 02:24 UTC, strongishllama commented on system/modules/insights/templates/runInsight.tpl.php
> +  $("#pdf-close-modal").click(function(event) {
I believe we're working on phasing out JQuery, it might be worth rewriting this in vanilla Javascript. Thoughts @adam-buckley?

2021-08-17 02:24 UTC, strongishllama commented on system/modules/insights/actions/members/editMembers.php
> +            //if (!InsightService::getInstance($w)->IsMember($insight_class_name, $user->id)){
If the commented code in this action isn't needed, it would be worth removing it.

2021-08-17 02:34 UTC, strongishllama commented on system/modules/insights/templates/runInsight.tpl.php
> +  $("#pdf-close-modal").click(function(event) {
@Tinystep1 Update on this. Adam said it's worth rewriting in vanilla Javascript. Reach out if you have issues with this!

2021-08-20 04:40 UTC, Tinystep1 commented on system/modules/insights/actions/members/editMembers.php
> +            //if (!InsightService::getInstance($w)->IsMember($insight_class_name, $user->id)){
Thanks for picking that up. Somehow missed the code clean-up on this page.

2021-08-20 04:42 UTC, Tinystep1 commented on system/modules/insights/templates/runInsight.tpl.php
> +  $("#pdf-close-modal").click(function(event) {
Your second dot point is correct. You have to create a template with the correct category. The specifics of that are included on my most recent docs pull-request on writing insights. But yes, it also works without a template.

2021-08-20 04:46 UTC, Tinystep1 commented on system/modules/insights/templates/runInsight.tpl.php
> +  $("#pdf-close-modal").click(function(event) {
The hotfix for array_key_exists() says it has some checks in progress, and is up for re-review.

2021-08-22 22:52 UTC, strongishllama commented on system/modules/insights/templates/runInsight.tpl.php
> +  $("#pdf-close-modal").click(function(event) {
Sounds good, looks like the tests are failing on that pull request.

2021-08-22 22:54 UTC, strongishllama approved these changes

2021-08-24 23:50 UTC, strongishllama approved these changes

2021-08-25 02:16 UTC, merged