Feat: Hide columns on list tasks
2pisoftware/cmfive-core pull request #164
Opened 2022-02-15 00:53 UTC by Dane-2pi

## Checklist
- [x] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
- [x] I've added comments to any new methods I've created or where else relevant.
- [ ] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [ ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description
Add feature to hide select columns in the listtasks partial 

## Changelog
- add hide_columns param
- add support in the template

refs: 2198
issues:

## Other Information

Docs pull request:

2022-02-15 01:02 UTC, adam-buckley approved these changes

2022-02-15 01:04 UTC, adam-buckley approved these changes

2022-02-15 06:03 UTC, careck commented on system/modules/task/partials/actions/listtasks.php
> +	$w->ctx("hide_columns", array_key_exists('hide_columns', $params)? $params['hide_columns'] : false);
I would just have the one parameter "columns_to_hide" because it's existing or absence can trigger the relevant code further down.

2022-02-15 06:04 UTC, careck commented on system/modules/task/partials/templates/listtasks.tpl.php
> +    if ($hide_columns)
As per my comment above, this parameter is unnecessary because we can just check the existence of "columns_to_hide" to achieve the same effect.

2022-02-16 23:26 UTC, adam-buckley commented on system/modules/task/partials/actions/listtasks.php
> +	$w->ctx("hide_columns", array_key_exists('hide_columns', $params)? $params['hide_columns'] : false);
There was a reason we wanted 2 variables though. We manipulate the array of columns to hide and so I figured it would be cleaner to separate concerns.

2022-02-16 23:28 UTC, adam-buckley requested changes
Please format the code as per our phpcs rules

2022-02-16 23:28 UTC, adam-buckley commented on system/modules/task/partials/actions/listtasks.php
> +    {
Why are all the brackets of the if statements on new lines? This doesn't match our code standard... maybe the code sniffer is configured wrong?

2022-02-17 02:19 UTC, careck commented on system/modules/task/partials/actions/listtasks.php
> +	$w->ctx("hide_columns", array_key_exists('hide_columns', $params)? $params['hide_columns'] : false);
That's OK, you can send a new parameter into the ctx but it doesn't have to be a second parameter to the partial. Easy to write:
`$w->ctx("hide_columns", array_key_exists("columns_to_hide", $params));`
We shouldn't expose internal workings to the external interface.

2022-02-17 22:40 UTC, adam-buckley approved these changes

2023-06-22 02:43 UTC, adam-buckley approved these changes

2023-09-25 04:30 UTC, Dane-2pi commented
@adam-buckley , is this good to be merged and closed out? Looks like we were both happy with it some time ago

2023-12-13 03:52 UTC, Dane-2pi commented
has been merged in some time ago. closing

2023-12-13 03:52 UTC, closed without merging