Add move action/fix duration display for timelogs
2pisoftware/cmfive-core pull request #179
Opened 2023-03-27 04:43 UTC by dragonflyfree

## Checklist
- [x] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
- [N/A] I've added comments to any new methods I've created or where else relevant.
- [N/A] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [N/A] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description
Added move action for more intuitive UI for moving timelogs between tasks. Fixed bug where timelog lists were attempting to get the duration of active timelogs.

## Changelog
. added timelog/actions/move.php
. added timelog/templates/move.tpl.php
. modified timelog/partials/templates/listtimelog.tpl.php to display move button when viewing timelogs as part of a task
. modified timelog/partials/templates/listtimelog.tpl.php to display "See Timer" for duration field of active timelogs
. modified timelog/actions/index.tpl.php to display move button when viewing timelogs on the timelog dashboard

2023-03-27 04:52 UTC, careck commented on system/modules/timelog/actions/move.php
> +    $w->ctx('redirect', Request::string("redirect", ''));
style: use double quotes for all strings unless the string contains double quotes.

2023-03-27 05:18 UTC, dragonflyfree commented on system/modules/timelog/actions/move.php
> +    $w->ctx('redirect', Request::string("redirect", ''));
Added new commit, is that what you're after? Or did I go overboard 😅

2023-03-27 22:38 UTC, adam-buckley requested changes

2023-03-27 22:38 UTC, adam-buckley commented on system/modules/timelog/actions/move.php
> +            $w->msg("Timelog not found", "/timelog");
You'll need the $w->out messages here instead of in post

2023-03-27 22:38 UTC, adam-buckley commented on system/modules/timelog/actions/move.php
> +        if (!empty($additional_form_fields[0])) {
I dont think we'll need additional fields here, it should just be the task autocomplete field

2023-03-27 22:38 UTC, adam-buckley commented on system/modules/timelog/actions/move.php
> +        usort($users, function ($a, $b) {
Same here, the user list can go

2023-03-27 22:38 UTC, adam-buckley commented on system/modules/timelog/actions/move.php
> +        $w->out("No Timelog to move");
Sorry I misunderstood when we chatted yesterday, in POST there is no UI, so we should be using the $w->msg functions. And you should be redirecting to ```$redirect``` instead of ```/timelogs```

2023-03-27 22:38 UTC, adam-buckley commented on system/modules/timelog/actions/move.php
> +    $timelog->setComment(Request::string("description"));
There is no description here (I think?) so no need for this

2023-03-27 22:38 UTC, adam-buckley commented on system/modules/timelog/actions/move.php
> +        if (!empty($additional_form_fields[0])) {
Nevermind, I just checked the template

2023-03-27 22:38 UTC, adam-buckley commented on system/modules/timelog/templates/move.tpl.php
> +        $("#timelogForm").on("submit", function() {
This code can go I think

2023-03-27 23:05 UTC, dragonflyfree commented on system/modules/timelog/actions/move.php
> +        if (!empty($additional_form_fields[0])) {
additional fields should stay?

2023-03-27 23:18 UTC, dragonflyfree commented on system/modules/timelog/actions/move.php
> +        $w->out("No Timelog to move");
I'm partially going off of what's in edit.php, for move_GET I do `$redirect = Request::string("redirect", "");` and then when doing error checks the messages should be `$w->msg("Timelog not found", $redirect);`?
And for move_POST it's msg or error? edit_POST uses error, should just copy that no?

2023-03-29 23:16 UTC, adam-buckley commented on system/modules/timelog/actions/move.php
> +        if (!empty($additional_form_fields[0])) {
Yeah I think these ones need to stay

2023-03-29 23:16 UTC, adam-buckley commented on system/modules/timelog/actions/move.php
> +        $w->out("No Timelog to move");
$w->error is fine yeah. They both do the same thing except $w->error shows up in a red alert instead of blue... so $w->error makes a lot more sense actually

2023-03-29 23:19 UTC, adam-buckley approved these changes
Can merge pending demo

2023-04-03 03:51 UTC, merged