Feature/name email search list users
2pisoftware/cmfive-core pull request #184
Opened 2023-04-06 06:48 UTC by 2piJareem

## Checklist
- [x] I'm using the correct PHP Version (8.1).
- [x] I've added comments to any new methods I've created or where else relevant.
- [x] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [x] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description
Added Lastname and Email filter to List Users function within Admin menu

## Changelog
- modules/admin/actions/users.php  Added filter functionality
- modules/admin/templates/users.tpl.php  Added filter to template

refs:
issues:

## Other Information

Docs pull request:

2023-05-18 04:49 UTC, adam-buckley requested changes

2023-05-18 04:49 UTC, adam-buckley commented on system/templates/base/.gitignore
> +package-lock.json
Remove this and add package-lock.json back in

2023-07-06 05:17 UTC, 2piJareem commented on system/templates/base/.gitignore
> +package-lock.json
Sorry I didn't see this earlier.  when I remove the dist/ folder from .gitignore I get 8 files form the dist folder and below that want to be committed - Do we want to commit these files as well?
![Screenshot 2023-07-06 at 3 17 12 pm](https://github.com/2pisoftware/cmfive-core/assets/122758853/8ae08e30-fba6-4af3-9b34-9a8f192594ac)

2023-08-16 06:01 UTC, adam-buckley requested changes

2023-08-16 06:59 UTC, 2piJareem commented on .gitignore
> +system/templates/base/package-lock.json
Removed

2023-08-16 07:08 UTC, 2piJareem commented on system/modules/insights/actions/index.php
> +function checkUserAccess(Web $w, $group, $user_id) : bool {
After putting the function into InsightService
eg     public function checkUserAccess(Web $w, $group, $user_id): bool

How does the action function find the function in the service class?  
I get "undefined function" if called as "checkUserAccess(...)"

and "Non static method 'checkUserAccess' should not be called statically."  if I called as "InsightService::checkUserAccess(...)"

2023-08-16 22:26 UTC, 2piJareem commented on system/modules/insights/actions/index.php
> +function checkUserAccess(Web $w, $group, $user_id) : bool {
sorted

2023-08-16 22:29 UTC, 2piJareem commented on system/modules/insights/actions/index.php
> +function checkUserAccess(Web $w, $group, $user_id) : bool {
btw  should "checkUserAccess(...)" function go in InsightService or AuthService?

2024-03-18 05:31 UTC, adam-buckley commented
Moved to draft cause I dont think this PR offers anything anymore. Holding off to make sure soon

2024-12-16 23:16 UTC, closed without merging