Feat/auth bs5 conversion
2pisoftware/cmfive-core pull request #263
Opened 2024-02-21 02:02 UTC by tynanmatthews

## Checklist
- [ ] I'm using the correct PHP Version (8.1 for current, 7.4 for legacy).
- [ ] I've added comments to any new methods I've created or where else relevant.
- [ ] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [ ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description

## Changelog
- migrated from axios to fetch for login
- converted from foundation to Bootstrap5 for auth module
- added database seeds admin playwright utility function

refs:
issues:

## Other Information

Docs pull request:

2024-02-21 04:20 UTC, adam-buckley requested changes

2024-02-23 02:43 UTC, tynanmatthews commented on system/modules/auth/templates/layout-bootstrap-5.tpl.php
>  $theme_setting = AuthService::getInstance($w)->getSettingByKey('bs5-theme');
*facepalm*

2024-02-23 03:05 UTC, adam-buckley approved these changes

2024-02-28 02:46 UTC, DerekCrannaford commented
> Login fails when testing locally, locking while I find out why

DC says : manually tested == login=OK, failed_login=OK, MFA_login=OK, ForgotPassword=Dialogs=OK (no mail sent from my setup)

Playwright tests: 
 - cannot seem to pass timelog tests?

2024-02-28 03:12 UTC, merged