Fix CI for new cmfive docker image
2pisoftware/cmfive-core pull request #269
Opened 2024-02-23 05:31 UTC by mattbell87

This fixes the cmfive-core CI so that it passes for the new cmfive image.

Changes to note:

- Each step adapted for minor differences for alpine
- Cmfive and root users specified for each docker exec step
- Boilerplate develop branch is checked out and used in the test
- Current cmfive-core commit is checked out and used in the test
- Dependency on boilerplate docker-compose was dropped, now uses plain docker (reason is so that the CI defines its own method)
- Gets container logs when there's a failure
- Composer module caching (may not be working properly yet)

This has been thoroughly tested, some playwright tests aren't passing at the moment, however without them the workflow passes.

2024-02-23 07:16 UTC, chris-bateman approved these changes

2024-02-23 09:51 UTC, mattbell87 commented on .github/workflows/ci.yml
> +          docker exec -t cmfive sh -c "DB_HOST=mysql-8 DB_USERNAME=root DB_PASSWORD=root DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php testDB setup; exit \$?";
I get this error when I use the cmfive_test user:
![image](https://github.com/2pisoftware/cmfive-core/assets/2722612/d7b56d26-531f-4f6a-8206-85cfe74766a7)

2024-02-23 19:49 UTC, chris-bateman commented on .github/workflows/ci.yml
> +          docker exec -t cmfive sh -c "DB_HOST=mysql-8 DB_USERNAME=root DB_PASSWORD=root DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php testDB setup; exit \$?";
Ok and these are specific to just the testing framework?

2024-02-24 03:25 UTC, mattbell87 commented on .github/workflows/ci.yml
> +          docker exec -t cmfive sh -c "DB_HOST=mysql-8 DB_USERNAME=root DB_PASSWORD=root DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php testDB setup; exit \$?";
Yeah I believe it's just for filling the db with test data. You'd have to ask Adam for any detail beyond that. But yeah everything in there just gets dropped at the end of the workflow anyway 👍

2024-02-26 00:54 UTC, adam-buckley requested changes
Locking until Matt makes changes as discussed to the setup of cmfive-core in CI

2024-02-26 06:40 UTC, mattbell87 commented
> Locking until Matt makes changes as discussed to the setup of cmfive-core in CI

Hey @adam-buckley here are some changes:

- It installs the core with cmfive.php and specifies the branch using an environment variable
- Both are still cloned to the CI workspace and symlinked so that playwright can see all the tests
- A dedicated volume is used inside the container so that the symlink doesn't conflict
- With @tynanmatthews changes it's all passing!

2024-02-26 23:09 UTC, adam-buckley approved these changes

2024-02-26 23:10 UTC, merged