Display upload sizes in MultiFileUpload and attachment view
2pisoftware/cmfive-core pull request #276
Opened 2024-03-01 00:47 UTC by dragonflyfree

## Checklist
- [x] I'm using the correct PHP Version (8.1 for current, 7.4 for legacy).
- [x] I've added comments to any new methods I've created or where else relevant.
- [] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [ ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description
Display upload sizes in MultiFileUpload and attachment view

## Changelog
- Add file size to file preview partial
- Add ability to grab file size from Attachment model
- Add display for total MultiFileUpload upload size, also displays sizes for each individual file in the MultiFileUpload

refs:
issues:

## Other Information

Docs pull request:

2024-03-01 03:34 UTC, adam-buckley requested changes

2024-03-01 03:34 UTC, adam-buckley commented on system/modules/file/models/Attachment.php
> +    public function getSize(): string
I wonder if it would be good to have 2 versions of this function. One to return just the size, and a human readable version. Cause we may want to tally the sizes or something, and it would be confusing as to why this function doesn't do what the File object version does despite having the same name. Or maybe just rename it to something like ```getHumanReadableSize()```?

2024-03-15 01:26 UTC, adam-buckley requested changes

2024-03-15 01:26 UTC, adam-buckley commented on system/modules/file/models/Attachment.php
> +    public function getSize(): string
@dragonflyfree

2024-03-15 01:26 UTC, adam-buckley commented on system/templates/base/src/js/components/MultiFileUpload.ts
> +function formatBytes(bytes, decimals = 2) {
I think it would be best to have this in a util class as an exported function that can be imported here

2024-07-10 08:05 UTC, chris-bateman commented
@dragonflyfree can you look at this and work with @DaltJM on deploying it?

2024-07-24 07:01 UTC, dragonflyfree commented
@chris-bateman finishing up what Adam asked, then will get onto this with @DaltJM :)

2024-09-25 01:30 UTC, chris-bateman commented
@dragonflyfree bump on this?

2024-09-25 02:40 UTC, DerekCrannaford commented
> @dragonflyfree bump on this?

Needs merge back from develop (for is_mobile test flag) and PR366 for timezone - then tests can pass against docker/alpine.
Verified all tests can pass locally, with those merges.

2024-09-27 03:40 UTC, dragonflyfree commented
> > @dragonflyfree bump on this?
> 
> Needs merge back from develop (for is_mobile test flag) and PR366 for timezone - then tests can pass against docker/alpine. Verified all tests can pass locally, with those merges.

PR366 got merged into `main`, which was then merged into `develop`, so both sets of changes should now be in this branch. Will test everything real quick to make sure all is well and good

2024-12-16 23:16 UTC, closed without merging