Fix/display billable hours
2pisoftware/cmfive-core pull request #294
Opened 2024-04-24 01:13 UTC by timl07

## Checklist
- [ ] I'm using the correct PHP Version (8.1 for current, 7.4 for legacy).
- [ ] I've added comments to any new methods I've created or where else relevant.
- [ ] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [ ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description

## Changelog

refs:
issues:

## Other Information

Docs pull request:

2024-04-24 04:07 UTC, careck requested changes

2024-04-24 04:07 UTC, careck commented on system/modules/task/models/TaskTime.php
> +    public function getTotalTimeByTimeType() {
This function should rather be in the TaskService class as it collects results from multiple tasks. Functions in DbObject derived classes should pertain only to this particular instance.

2024-04-24 04:07 UTC, careck commented on system/modules/task/models/TaskTime.php
> +    public function getTotalTimeByBillable() {
Same as above. This function belongs to TaskService class as it collects results for multiple tasks.

2024-04-24 05:38 UTC, timl07 commented on system/modules/task/models/TaskTime.php
> +    public function getTotalTimeByBillable() {
Understood, moved.

2024-05-05 04:14 UTC, dragonflyfree approved these changes

2024-07-10 07:59 UTC, chris-bateman commented
@dragonflyfree can you work on these merge issues?

2024-09-08 06:52 UTC, closed without merging