Feat: Webauthn based authentication
2pisoftware/cmfive-core pull request #327
Opened 2024-08-07 08:12 UTC by mattbell87

## Checklist
- [ ] I'm using the correct PHP Version (8.1 for current, 7.4 for legacy).
- [ ] I've added comments to any new methods I've created or where else relevant.
- [ ] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [ ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description

## Changelog

refs:
issues:

## Other Information

Docs pull request:

2024-08-08 05:08 UTC, adam-buckley requested changes

2024-08-08 05:08 UTC, adam-buckley commented on system/modules/timelog/tests/acceptance/playwright/timelog.test.ts
> +    await TaskHelper.addMemberToTaskgroup(page, taskgroup, taskgroupID, "Admin Admin", "OWNER");
We'll need a better way of dictating what admin user should be used to run the tests but by default the test setup tool names it "admin admin" so this change will break tests in Github Actions - please revert

2024-08-08 06:00 UTC, mattbell87 commented on system/modules/timelog/tests/acceptance/playwright/timelog.test.ts
> +    await TaskHelper.addMemberToTaskgroup(page, taskgroup, taskgroupID, "Admin Admin", "OWNER");
Oops, these changes were not meant to be here anyway!

2024-08-16 07:30 UTC, adam-buckley requested changes

2024-08-16 07:30 UTC, adam-buckley commented on system/modules/admin/install/migrations/20240808181623-AdminMigration9izg7_TestMigration.php
> +    public function up()
This commit from the test system shouldn't be here

2024-08-16 07:30 UTC, adam-buckley commented on system/modules/admin/install/migrations/20240808181623-AdminMigration9izg7_TestMigration.php
> +    public function up()
migration*

2024-08-16 07:36 UTC, adam-buckley commented on system/modules/auth/actions/ajax_register_authenticator.php
> +        'cmfive.com',              //ID
I know this is still draft but this name/domain should be configurable via cmfive Config

2024-08-16 07:36 UTC, adam-buckley commented on system/modules/auth/actions/ajax_register_authenticator.php
> +        'admin admin',                          //Display name
Same for the name

2024-08-16 07:36 UTC, adam-buckley commented on system/modules/auth/actions/ajax_register_authenticator.php
> +            $rpEntity,
Do we also need to store this status in the database somewhere? From memory we do it for MFA

2024-12-16 23:16 UTC, closed without merging