feat: Get config from parameter store and secrets manager
2pisoftware/cmfive-core pull request #334
Opened 2024-08-13 05:44 UTC by mattbell87

## Checklist
- [ ] I'm using the correct PHP Version (8.1 for current, 7.4 for legacy).
- [ ] I've added comments to any new methods I've created or where else relevant.
- [ ] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [ ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description

## Changelog

refs:
issues:

## Other Information

Docs pull request:

2024-08-15 01:14 UTC, adam-buckley requested changes

2024-08-15 01:14 UTC, adam-buckley commented on system/classes/Config.php
> +    public static function setFromParameterStore(string $parameterName, string $bucket, string $key): void
The S3 bucket and key should be optional with a check to see if they're set

2024-08-15 04:22 UTC, mattbell87 commented on system/classes/Config.php
> +    public static function setFromParameterStore(string $parameterName, string $bucket, string $key): void
Done

2024-08-16 06:11 UTC, adam-buckley requested changes

2024-08-16 06:11 UTC, adam-buckley commented on system/classes/Config.php
> +    public static function setFromParameterStore(string $parameterName, ?string $bucket = null, ?string $key = null): void
I just noticed, and I don't know if it's actually important but the "self" reference is usually all lowercase

2024-08-16 06:38 UTC, mattbell87 commented on system/classes/Config.php
> +    public static function setFromParameterStore(string $parameterName, ?string $bucket = null, ?string $key = null): void
You are right, all fixed

2024-08-16 07:25 UTC, adam-buckley approved these changes

2024-08-16 07:27 UTC, merged