updated tests for mobile, improved layouts for mobile
2pisoftware/cmfive-core pull request #340
Opened 2024-08-23 06:24 UTC by dragonflyfree

## Checklist
- [x] I'm using the correct PHP Version (8.1 for current, 7.4 for legacy).
- [x] I've added comments to any new methods I've created or where else relevant.
- [x] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [x] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description

Improves layout on mobile for some pages, adds mobile testing capabilities to core playwright tests

## Changelog

refs:
issues:

## Other Information

Docs pull request:

2024-08-29 23:53 UTC, mattbell87 approved these changes

2024-08-30 00:10 UTC, adam-buckley requested changes

2024-08-30 00:10 UTC, adam-buckley commented on system/classes/HtmlBootstrap5.php
> +        $buffer .= "<div class='d-block d-md-none' style='padding-top: 2ch;'>";
I'd probably prefer to not see esoteric units of measurement in CSS, bootstrap also has padding classes so this can be replaces with the bootstrap class ```pt-[1-4]```

2024-08-30 05:00 UTC, adam-buckley approved these changes

2024-08-30 06:43 UTC, merged