Feat/finish new designs migration
2pisoftware/cmfive-core pull request #389
Opened 2024-10-18 03:43 UTC by dragonflyfree

## Checklist
- [x] I'm using the correct PHP Version (8.1 for current, 7.4 for legacy).
- [x] I've added comments to any new methods I've created or where else relevant.
- [x] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [x] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).

## Description

Various changes to Tag and Form modules, changes to Bootstrap5 code, Vue2 to Vue3 (yet to be complete for Form module, may be required in Admin module, for example in the users list? perhaps?) conversion, etc.

## Changelog

refs:
issues:

## Other Information

Docs pull request:

2024-10-21 23:06 UTC, MaddyUnderStars commented
Below is a copy of my last PR #384 as this one is replacing it.
It's strictly *my* work on this migration as I'm not completely aware of what Adam and Claire have done.

general goals:
- migrate pages to bootstrap5 theme.
- - this theme does not include jquery, so it also requires rewriting a lot of systems to use plain js
- while I was writing something due to prev point, I might as well fix some bugs or improve small things
- lastly, if a page was written in plain html, it was easier to just make use of the form generation code or such in php since that already has all the bootstrap5 classes.

modules migrated:
- tag
- task
- timelog
- favourites

by page:
- /task/index ( dashboard )
- /task-group/viewtaskgrouptypes ( manage task groups )
- - uses quill editor instance of a plain text area
- /task/taskweek ( activity )
- /task/tasklist ( task list )
- /task/edit ( task view/edit )
- - only the edit/view and timelog tabs have been migrated currently, as the others are partials
- /task-group/viewmembergroup ( task group members/details page )
- /task-group/viewtaskgroup modal ('edit task group' button in viewmembergroup )
- /task/partials/listtasks
- /task/subscriber
- /task/subscriber/add
- /timelog/partial/listtimelog
- /timelog/index
- /timelog/edit
- /timelog/move
- /task-group/movetaskgroup modal
- /task-group/addgroupmembers

jquery:
- new php class Html5Autocomplete for multiselect free-form text input with autocomplete drop downs included with tom select
- removed jquery usage for CKEDITOR from html::form
- rewrite tags module client js to remove jquery dep.
- - tags module is now included in /system/templates/base/ so as to only include a single tags manager per page vs per inclusion of the partial
- - tags module now fetches tags via ajax
- - can now remove or add multiple tags at once via the modal (#250)
- Favourites
- - FavouriteService::getFavouriteButton now deprecated in favour of getBootstrapButton
- - Migrated favourites list modal to bootstrap
- 
# Screenshots and video ( as of 14/10 )

<details>
	<summary>/task/index</summary>
	<img src="https://github.com/user-attachments/assets/b25c015c-8810-44e8-99bf-b741c61ad56f"/>
</details>

<details>
	<summary>task-group/viewtaskgrouptypes</summary>
	<img src="https://github.com/user-attachments/assets/ec4201fb-a644-4921-b43e-09c3fe4b7825"/>
	<img src="https://github.com/user-attachments/assets/3212fe62-a65b-45f7-b27d-25d54c20476c"/>
</details>

<details>
	<summary>/task/taskweek</summary>
	<img src="https://github.com/user-attachments/assets/a68d7948-ba55-41e3-8d72-db707f19d0bc"/>
</details>

<details>
	<summary>/task/tasklist</summary>
	<img src="https://github.com/user-attachments/assets/75a7eda4-0030-415b-b401-036ca3e5a40a"/>
</details>

<details>
	<summary>/task/edit</summary>
	<img src="https://github.com/user-attachments/assets/576f8e24-95bd-4588-9825-f2169719e23e"/>
	<img src="https://github.com/user-attachments/assets/4a65fff3-b2d4-45db-af7a-a8fa860b7add"/>
	<img src="https://github.com/user-attachments/assets/ede0a0bb-bece-46b7-983a-a97dbbabbd8b">
	<video src="https://github.com/user-attachments/assets/f58a92f7-646c-4db4-ab7a-dfd1d854abf8"/>
</details>

<details>
	<summary>/task-group/viewmembergroup and /task/listtasks partial</summary>
	<img src="https://github.com/user-attachments/assets/98ac058b-157a-4753-a05b-fe49fe1d6fd6"/>
	<img src="https://github.com/user-attachments/assets/70c6610f-1836-49e4-854e-a39a89af73b5"/>
</details>

<details>
	<summary>/task-group/viewtaskgroup modal</summary>
	<img src="https://github.com/user-attachments/assets/eeeda059-8b6d-4264-96a8-7d28c152c50c"/>
</details>

<details>
	<summary>/task/subscriber</summary>
	<img src="https://github.com/user-attachments/assets/d0c9b8a2-1f3c-4a1e-83a6-75f5076a0f60"/>
	<img src="https://github.com/user-attachments/assets/c1c5dd7c-65fb-4943-a6da-fd74eef7942d"/>
</details>

<details>
	<summary>/task/listtimelog</summary>
	<img src="https://github.com/user-attachments/assets/d4a4e24e-bf54-4b2e-a3a3-13aa6f9c413a"/>
	<img src="https://github.com/user-attachments/assets/8d7d79d6-e132-4fbc-98a5-07ad537ffcf0"/>
</details>

<details>
	<summary>/timelog/index</summary>
	<img src="https://github.com/user-attachments/assets/975575d8-4221-4d90-8fc6-f245b0074f2a"/>
</details>

<details>
	<summary>/timelog/edit</summary>
	note: the assigned user field is only visible as admin user, like it is currently
	<img src="https://github.com/user-attachments/assets/044b0248-eb05-4e9e-944a-be16917b5c5e"/>
</details>

<details>
	<summary>/timelog/move</summary>
	<img src="https://github.com/user-attachments/assets/fbfe35bd-6749-45a4-859a-6f84d2f7d390"/>
</details>

<details>
	<summary>/task-group/movetaskgroup modal</summary>
	<img src="https://github.com/user-attachments/assets/1aab870c-91a6-4f99-ad28-a77d2f176f93"/>
	<img src="https://github.com/user-attachments/assets/e9ab1146-dba7-4cc1-81fe-f7bfecb927a8"/>
</details>

<details>
	<summary>/task-group/addgroupmembers modal</summary>
	<img src="https://github.com/user-attachments/assets/3f22c277-50c1-41d8-942a-c19772d8e4f9"/>
</details>

<details>
	<summary>add tags modal</summary>
	<video src="https://github.com/user-attachments/assets/30741181-8c68-405a-9ec7-d7b89dbc6346"/>
</details>

<details>
	<summary>favourites modal</summary>
	<img src="https://github.com/user-attachments/assets/f5fde495-6eb9-4e48-8204-79acf8d4ff5a"/>
</details>

2024-10-22 00:39 UTC, MaddyUnderStars commented on system/modules/task/templates/edit.tpl.php
> +            <a href="#attachments">Attachments</a>
TODO: add counts to the tab headers like timelog has

2024-11-11 05:59 UTC, adam-buckley requested changes

2024-11-11 05:59 UTC, adam-buckley commented on system/modules/form/templates/application/edit_member.tpl.php
> +<?php echo $form; ?>
Another closing php tag

2024-11-11 22:49 UTC, MaddyUnderStars commented on system/html.php
> +        $buffer .= "<script>document.addEventListener('DOMContentLoaded', () => { [...document.querySelectorAll('textarea.ckeditor')].forEach(x => { CKEDITOR.replace(x) }) })</script>";
It returns an Array-like [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) structure which you cannot directly iterate over with .forEach

2024-11-28 02:59 UTC, adam-buckley commented
![image](https://github.com/user-attachments/assets/75dbd57c-43b4-4ad6-b5fa-609054385736)
Tests passing

2024-12-03 23:20 UTC, MaddyUnderStars commented on system/templates/base/src/js/components/MultiSelect.ts
Yes, the autocomplete class was just renamed from multiselect initially. It does all the same stuff except it also allows some things such as:
- autocomplete text input
- fetching data from some endpoint
- adding/removing data from the list via some endpoint
- thats all I can remember atm

2024-12-04 01:05 UTC, iceaxeliehne approved these changes

2024-12-04 01:44 UTC, DerekCrannaford commented on system/modules/auth/actions/login.php
> +        $w->out((new JsonResponse())->setErrorResponse("Please enter your login and password", "Please enter your login and password"));
this $w->out::JSON strategy is known to make viewable JSON gibberish & error fragments in cases of low level exception events cascading from $w calls &/or hooks.
Can the entirety of POST have a try/catch wrapper with a stable-but-meaningless "System FAILED" JSON placeholder?

2024-12-04 01:47 UTC, DerekCrannaford commented on system/modules/auth/templates/login.tpl.php
> +                    return response.json()
Maybe here is where to attend to : https://github.com/2pisoftware/cmfive-core/pull/389/files#r1868582045
???

2024-12-04 02:51 UTC, DerekCrannaford commented on system/modules/form/actions/application/attach_form.php
> +    if (empty($available_forms)) {
This is an awkward bounce when in modal?

2024-12-04 02:58 UTC, DerekCrannaford commented on system/modules/form/actions/edit.php
>  function edit_GET(Web $w)
This wants to be in a modal, but it isn't?
![image](https://github.com/user-attachments/assets/64a78bf8-4632-45a9-a476-376990c66e49)

![image](https://github.com/user-attachments/assets/7dfbb55b-77cc-4cfe-abd8-7b996f2bb3b8)

2024-12-05 02:27 UTC, MaddyUnderStars requested changes
![image](https://github.com/user-attachments/assets/5fbde9d4-3805-4f91-aa35-b39aaa90efdb)
![image](https://github.com/user-attachments/assets/9def5ae9-82d3-42f1-a182-ef34119ef8d8)
![image](https://github.com/user-attachments/assets/459d0dcc-8e19-467a-99da-d6cf97de8a18)

on form/show/:id event modal, select includes multiple "-- select --"

2024-12-05 02:27 UTC, MaddyUnderStars commented on system/modules/report/actions/createreport.php
> +                "value" => Request::string("module"),
```suggestion
                "selected_option" => Request::string("module"),
```

2024-12-05 02:27 UTC, MaddyUnderStars commented on system/modules/report/actions/createreport.php
> +                "value" => Request::int("report_connection_id"),
```suggestion
                "selected_option" => Request::int("report_connection_id"),
```

2024-12-05 02:27 UTC, MaddyUnderStars commented on system/modules/tag/partials/templates/listTags.tpl.php
> +    <style>
this embedded style should should be enqueued in the action instead

2024-12-05 02:27 UTC, MaddyUnderStars commented on system/modules/task/actions/tasklist.php
> +            "value" => !empty($assignee_id) ? $assignee_id : null,
```suggestion
            "selected_option" => !empty($assignee_id) ? $assignee_id : null,
```

2024-12-05 02:27 UTC, MaddyUnderStars commented on system/modules/task/actions/tasklist.php
> +            "value" => !empty($creator_id) ? $creator_id : null,
```suggestion
            "selected_option" => !empty($creator_id) ? $creator_id : null,
```

2024-12-05 02:27 UTC, MaddyUnderStars commented on system/modules/task/actions/tasklist.php
> +            "value" => !empty($task_type) ? $task_type : null,
```suggestion
            "selected_option" => !empty($task_type) ? $task_type : null,
```

2024-12-05 02:27 UTC, MaddyUnderStars commented on system/modules/task/actions/tasklist.php
> +            "value" => !empty($filter_urgent) ? "Urgent" : (!empty($task_priority) ? $task_priority : null),
```suggestion
            "selected_option" => !empty($filter_urgent) ? "Urgent" : (!empty($task_priority) ? $task_priority : null),
```

2024-12-05 02:27 UTC, MaddyUnderStars commented on system/modules/task/actions/tasklist.php
> +            "value" => !empty($task_status) ? $task_status : null,
```suggestion
            "selected_option" => !empty($task_status) ? $task_status : null,
```

2024-12-05 02:27 UTC, MaddyUnderStars commented on system/modules/task/actions/tasklist.php
> +            "value" => $is_closed,
```suggestion
            "selected_option" => $is_closed,
```

2024-12-05 02:27 UTC, MaddyUnderStars commented on system/templates/base/package.json
>      "jquery": "^3.7.1",
should be removed?

2024-12-05 02:34 UTC, adam-buckley commented on system/modules/auth/actions/login.php
> +        $w->out((new JsonResponse())->setErrorResponse("Please enter your login and password", "Please enter your login and password"));
I'll put this in for post v6 changes

2024-12-05 05:07 UTC, adam-buckley commented on system/modules/auth/templates/profile.tpl.php
> +                            "canCreate" => true, // this shouldn't be here
Which one?

2024-12-05 05:12 UTC, adam-buckley commented on system/modules/file/templates/view.tpl.php
> +        echo "Owner: User (" . $user->id . ")";
Probably not, something for post v6

2024-12-05 05:12 UTC, adam-buckley commented on system/modules/file/templates/view.tpl.php
> +            bi-filetype-<?php echo end(explode(".", $attachment->filename)) ?>
Agreed, for post v6 as well

2024-12-05 05:14 UTC, adam-buckley commented on system/templates/base/package.json
>      "jquery": "^3.7.1",
Browser-process? I'm not sure what purpose it serves, post v6 check

2024-12-05 06:15 UTC, MaddyUnderStars commented on system/modules/auth/templates/profile.tpl.php
> +                            "canCreate" => true, // this shouldn't be here
the one in the highlighted code "this shouldn't be here". canCreate shouldn't be set to true for the profile language, it should have options set via I assume the lookup table?

2024-12-05 06:16 UTC, MaddyUnderStars commented on system/templates/base/package.json
>      "jquery": "^3.7.1",
I meant the jquery dependency

2024-12-05 06:25 UTC, adam-buckley commented
Oh right, not sure why that's there...

On Thu, Dec 5, 2024, 5:17 PM Madeline ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In system/templates/base/package.json
> <https://github.com/2pisoftware/cmfive-core/pull/389#discussion_r1870705337>
> :
>
> >      ***@***.***/core": "^2.11.8",
> -    "bootstrap": "^5.2.3",
> -    "bootstrap-icons": "^1.10.5",
> +    "bootstrap": "^5.3.3",
> +    "bootstrap-icons": "^1.11.3",
>      "browser-process": "0.0.1",
>      "codemirror": "^6.0.1",
>      "jquery": "^3.7.1",
>
> I meant the jquery dependency
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/2pisoftware/cmfive-core/pull/389#discussion_r1870705337>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMDB4HJ5BJ52O4UW5LQOAD2D7VV7AVCNFSM6AAAAABQFBXGKOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOBQGU3TEOJVGQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-12-05 22:52 UTC, adam-buckley approved these changes

2024-12-05 22:54 UTC, adam-buckley commented on system/templates/base/package.json
>      "jquery": "^3.7.1",
Pushed to post v6

2024-12-05 23:26 UTC, MaddyUnderStars commented
![image](https://github.com/user-attachments/assets/ca55c0e8-690e-4fe8-bf0b-c15dabf0e7b9)
![image](https://github.com/user-attachments/assets/4fbd3346-a2a6-48e8-974b-d82846913ae6)
Codemirror dark mode colours aren't set. Also, opening a modal reattaches codemirror so you get 2 inputs.

2024-12-09 01:45 UTC, MaddyUnderStars approved these changes

2024-12-09 02:51 UTC, merged