Hotfix: Prevent adding task subscribers with insufficient view permissions
2pisoftware/cmfive-core pull request #74
Opened 2020-10-07 22:46 UTC by Dark-Reef

- Added a check & error if the subscribed user has permissions to view the given task
- Added a hook to check if users still can view even after task group permission changes
- Task group permission check now works for the "ALL" role

2020-10-11 23:51 UTC, adam-buckley requested changes

2020-10-11 23:51 UTC, adam-buckley commented on system/modules/task/actions/subscriber/add.php
> +                if (!$task->canView($contact->getUser())) {
I just learned how to make comments on a line of code in github... please change this to be one if statement. Also calling $contact->getUser() 3 times is expensive-ish, please also assign this to a variable first.

2020-10-11 23:51 UTC, adam-buckley commented on system/modules/task/actions/subscriber/add.php
> +                        $user = $contacts->getUser();
This function callback is done on a single contact, so the variable should be called ```$contact``` not ```$contacts```... unless I'm missing something here

2020-10-11 23:51 UTC, adam-buckley commented on system/modules/task/models/TaskService.php
> +        if (!empty($permission_array[$role]) && !is_null($permission_array[$required_permission])) {
I can see why getting rid of the empty call was done, but it should be replaced with ```array_key_exists``` not ```is_null``` since null is never assigned and a missing key that doesn't exist would trigger a separate error when using ```is_null``` (the original reason for using the call to ```empty``` I think was to test if the array key existed).

2020-10-12 00:29 UTC, Dark-Reef commented on system/modules/task/actions/subscriber/add.php
> +                        $user = $contacts->getUser();
Yea the code is actually calling it on the single contact, but thats cos the function paramater was misspelled with an S. I'll fix that up

2020-10-14 01:11 UTC, merged