fix: Search results returning headers with no content
2pisoftware/cmfive-core pull request #76
Opened 2020-10-11 22:13 UTC by Dark-Reef

- Added a check so the headers in the search results are only added if the users have permission to view the content of the results

refs: 7881

2020-10-11 23:47 UTC, adam-buckley reviewed
Looks good! I'll verify it locally today

2020-10-14 01:24 UTC, adam-buckley commented
The display of this looks a little weird:
![image](https://user-images.githubusercontent.com/1585392/95932592-fb6a0c80-0e17-11eb-82a5-e9d7f8ad497a.png)

@strongishllama can you fix this to still show the class name of the result as was previously done but to display the "Insufficient privileges" message underneath.

2020-10-14 01:27 UTC, adam-buckley requested changes

2020-10-14 01:27 UTC, adam-buckley commented on system/modules/search/actions/results.php
> +                            $buffer .= "Insufficient permissions";
Since canList is false if we get here and the buffer is empty, it actually shouldn't even say "Insufficient permissions", it should display nothing I'm pretty sure.

2020-10-14 01:27 UTC, adam-buckley commented on system/modules/search/actions/results.php
> +                            $buffer .= "Insufficient permissions";
"here" being line 59

2020-10-27 23:39 UTC, strongishllama commented on system/modules/search/actions/results.php
> +                            $buffer .= "Insufficient permissions";
Implemented requested changes.

2020-12-10 00:17 UTC, DerekCrannaford approved these changes

2020-12-10 00:18 UTC, merged