Mitigate SQL Issues
2pisoftware/cmfive-core pull request #78
Opened 2020-10-11 22:28 UTC by strongishllama

2020-10-11 23:09 UTC, adam-buckley reviewed
Please add some documentation to cmfive.com on setting up reports for read only access. Separately, we'll need a way to let administrators know when the read only connection details are missing, preferably using a banner hook similar to what Derek implemented for tasks.

2020-10-14 00:07 UTC, strongishllama commented
Added a hook that will set the error variable in context. This will be picked up by the template and display the error as a warning message on all action for admins.

2020-10-14 02:20 UTC, adam-buckley requested changes

2020-10-14 02:20 UTC, adam-buckley commented on system/modules/report/report.hooks.php
> +function report_core_web_after(Web $w)
This isn't quite what I was after, this will stop the usage of the reports module all together. Instead it should just display a persistent banner to administrators that the connection config is missing, but not actually redirect anywhere or stop anything. A new hook called something like "core_template_administrator_notifications" should be invoked in the system/templates/layout.tpl.php and answered here in report hooks

2020-10-14 02:20 UTC, adam-buckley commented on system/modules/report/report.hooks.php
> +    if (empty($config)) {
This whole if statement should go as the one below does the correct thing

2020-10-14 21:33 UTC, strongishllama commented on system/modules/report/report.hooks.php
> +function report_core_web_after(Web $w)
Maybe I'm missing something but I don't believe this is stopping the usage/execution of anything. It's just setting a variable in the ctx if the user is an admin and the reports database config isn't setup correctly. See the code snippet from the template and the screenshot.

Something should be done in the future to make a notifications button feature as you mentioned earlier in the week, but I think this should be a separate task to allow propper planning and implementation.

```php
if (!empty($error)) {
    echo Html::alertBox($error, "warning");
} elseif (!empty($msg)) {
    echo Html::alertBox($msg);
}
```
![Screenshot_2020-10-15 Main - Home](https://user-images.githubusercontent.com/30204322/96047525-0167f800-0ec1-11eb-9eff-f97c62709300.png)

2020-10-14 21:33 UTC, strongishllama commented on system/modules/report/report.hooks.php
> +    if (empty($config)) {
Removed the unneeded if statement in the last commit.

2020-10-14 23:24 UTC, adam-buckley approved these changes

2020-10-15 00:01 UTC, merged