Hotfix/tasks vanish with html tag titles
2pisoftware/cmfive-core pull request #80
Opened 2020-10-13 00:09 UTC by DerekCrannaford

Not sure best approach for this = hotfix->master ... or ... refactor/feature->develop ??
Was requested as specific hotfix on helpdesk mail -> auto task creation.
Proof of concept for controlling tag display from 'dirty' input data.

2020-10-14 02:09 UTC, adam-buckley requested changes

2020-10-14 02:09 UTC, adam-buckley commented on system/classes/DbObject.php
> +                $this->$k = ($convert ? $this->readConvert($k, $row[$k], $entityDecode) : $row[$k]);
I'm still not 100% sold on this idea, purely because it doesn't allow selective decoding per field, e.g we wont want to encode/decode encrypted fields but this implementation is an all or nothing.

2020-10-14 02:09 UTC, adam-buckley commented on system/modules/task/actions/createtask.php
> +function createtask_GET(Web &$w) {
I'm not sure why github shows this whole file as a new addition, was this previously removed?

2020-10-14 02:09 UTC, adam-buckley commented on system/modules/task/actions/duplicatetask.php
> + * duplicates a task allong with comments and attachments
Similarly, no idea if anything has changed in this file it github shows that the entire thing is an addition

2020-10-14 02:09 UTC, adam-buckley commented on system/modules/task/models/Task.php
> +            return htmlentities($this->title);
This is not 100% fool proof, a different function in this class that accesses the title would also need to convert it. I think the best approach to this is to store the ```htmlentities``` version of dangerous user inputted data in the database, and not decode it before it goes in. We could write migrations to convert all existing data to the entities version. The advantage to this is that html will display everything as it should be. @careck what do you think?

2020-10-14 02:09 UTC, adam-buckley commented
Hold off on changing this until I speak to @careck

2020-10-14 03:03 UTC, DerekCrannaford commented on system/classes/DbObject.php
> +                $this->$k = ($convert ? $this->readConvert($k, $row[$k], $entityDecode) : $row[$k]);
"doesn't allow selective decoding per field"  
BUT
can allow selective per field type, so can easily skip encrypted fields, same as it originally only acted on date_or_datetime.
-----------------------------------------------------------------
public function readConvert($k, $v, $entityDecode)
    {
        if($entityDecode) {
            $v = html_entity_decode($v);
        }
        if (strpos($k, "dt_") === 0) {
            if (!empty($v)) {
                return $this->dt2Time($v);
            }
        } elseif (strpos($k, "d_") === 0) {
            if (!empty($v)) {
                return $this->d2Time($v);
            }
        }
        return $v;

2020-10-14 03:03 UTC, DerekCrannaford commented on system/modules/task/actions/createtask.php
> +function createtask_GET(Web &$w) {
line 65 : $task->fill($arr_req, true, true);

2020-10-14 03:03 UTC, DerekCrannaford commented on system/modules/task/actions/duplicatetask.php
> + * duplicates a task allong with comments and attachments
No changes - can't explain.

2020-10-14 03:06 UTC, DerekCrannaford commented on system/modules/task/models/Task.php
> +            return htmlentities($this->title);
Really important to avoid this scenario:

 --> user INPUT 
	= submit > < &
	= ENCODE as &gt &lt &amp
	= store encoded

 --> show in PAGE CONTENT 
	= appears as : > < &
     Is good!
	 
 --> show in INPUT field
	= appears as : &gt &lt &amp
	= user submits INPUT through ENCODING
	= is stored as &ampgt &amplt &ampamp
     Is bad and gets worse...

2020-10-14 03:08 UTC, adam-buckley commented on system/modules/task/actions/createtask.php
> +function createtask_GET(Web &$w) {
Oh yeah I see the change, but github highlights the whole file as green, which is unusual. My guess is the line endings changed?

2020-10-14 03:11 UTC, adam-buckley commented on system/modules/task/models/Task.php
> +            return htmlentities($this->title);
Ah yeah I forgot about input fields... maybe we should always htmlentitydecode input fields?

2020-10-14 23:04 UTC, adam-buckley commented on system/modules/task/models/Task.php
> +            return htmlentities($this->title);
After some research and discussion with Carsten, it turns out I'm wrong. We should be htmlentity-ing any output into the browser but the models, database etc. should never know about it. I'll discuss the fixes with you on mattermost

2021-01-12 23:42 UTC, adam-buckley commented
Closing for now, this needs _much_ more work

2021-01-12 23:42 UTC, closed without merging