feat: capability to update config registry from json
2pisoftware/cmfive-core pull request #82
Opened 2020-10-21 00:42 UTC by twje

feature is implemented to support future CICD development

2020-10-21 02:55 UTC, strongishllama requested changes

2020-10-21 02:55 UTC, strongishllama commented on system/classes/Config.php
> +        if (!isset($string)) { return; }
Replace the usage of isset() with empty(). isset() will return true on an empty string. See this [article](https://www.virendrachandak.com/techtalk/php-isset-vs-empty-vs-is_null/).

Also remove the usage of one line if statements. Our linter will complain about this as it's against the PSR-2 standard. This VS Code [extension](https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs) can help with that.

2020-10-21 03:45 UTC, strongishllama requested changes

2020-10-21 03:45 UTC, strongishllama commented on system/classes/Config.php
> +        if (empty($source)) { return; }
The other one line if statement.

2020-10-21 03:48 UTC, strongishllama commented
Another couple of things that I don't know if is worth halting the pull request or not (have to ask @adam-buckley) is adding a comment at the top of the new method as well parameter and return type declarations. [PHP DocBlocker](https://marketplace.visualstudio.com/items?itemName=neilbrayfield.php-docblocker) will help you with the comment. I've also emailed you a document outlying some of the new language features in PHP that include parameter and return type declarations.

2020-11-19 02:44 UTC, twje commented on system/classes/Config.php
> +        if (!isset($string)) { return; }
- !isset() changed to empty()
- vs psprc extension used to ensure PSR-2 compliance

2020-11-19 02:47 UTC, merged

2020-11-19 02:48 UTC, strongishllama requested changes

2020-11-19 02:48 UTC, strongishllama commented on system/classes/Config.php
> +    public static function extendFromJson($string)
Worth adding the parameter and return type hinting. So it would become ```extendFromJson(string $string): void```.

2020-11-19 02:48 UTC, strongishllama commented on system/classes/Config.php
> +    private static function merge($source, &$target)
I'd add a comment here are as well, even though it's a private method. Also, same as the above comment in regards to the type hinting.

2020-12-09 02:13 UTC, strongishllama commented on system/classes/Config.php
> +    public static function extendFromJson($string)
Making this as resolved as a separate PR has been made to fix it. #92

2020-12-09 02:13 UTC, strongishllama commented on system/classes/Config.php
> +    private static function merge($source, &$target)
Making this as resolved as a separate PR has been made to fix it. #92