fix: Report Service
2pisoftware/cmfive-core pull request #89
Opened 2020-11-19 02:18 UTC by DerekCrannaford

Good UserWhere From AllCalls

Report UserWhere being called by array, string and 'empty'
Then breaking anyway due to incorrect quote escapes
Fixes for versatile calls & forced SQL escaping
Tested Support:
/report/index?module=
/report/reportAjaxCategorytoType?id=_
/report/reportAjaxListModules

refs: clients assert reports dont work

2020-11-19 02:41 UTC, strongishllama requested changes
Looks good, just remove that commented var_dump on line 188. I'd be keen for @adam-buckley to approve this as well though before merging it. Just due to the importance of reports.

2020-11-19 02:43 UTC, strongishllama requested changes
Looks good! Just add the comments and type hinting as we discussed, cheers.

2020-11-19 23:40 UTC, DerekCrannaford commented
Added commit to include patches on RunReport vs ExeReport for membership rules to match those of getUserWhere
Added SQLI unit test for getUserWhere : php cmfive.php tests unit report

2020-11-20 00:38 UTC, adam-buckley requested changes

2020-11-20 00:38 UTC, adam-buckley commented on system/modules/report/models/ReportService.php
> +                $conferred[] = $this->getObject("ReportMember", ["report_id" => $id, "user_id" => $group->id, "is_deleted" => 0]);
Thinking about this again, there's still a chance that the member return here is null. before the return below we should be calling array_filter over this conferred variable which will strip out null values

2020-11-20 00:38 UTC, adam-buckley commented on system/modules/report/models/ReportService.php
> +        $myid[] = $this->_db->quote($id);
This is not the correct way to instantiate an array, even though this works it should be ```$myid = [$this->_db->quote($id)];```

2020-11-20 00:38 UTC, adam-buckley commented on system/modules/report/models/ReportService.php
> +     public function unitaryWhereToAndClause($where) {
Not PSR2 compliant

2020-11-20 00:57 UTC, DerekCrannaford commented on system/modules/report/models/ReportService.php
> +                $conferred[] = $this->getObject("ReportMember", ["report_id" => $id, "user_id" => $group->id, "is_deleted" => 0]);
+1

2020-11-20 01:00 UTC, DerekCrannaford commented on system/modules/report/models/ReportService.php
> +     public function unitaryWhereToAndClause($where) {
+1

2020-11-20 01:02 UTC, DerekCrannaford commented on system/modules/report/models/ReportService.php
> +        $myid[] = $this->_db->quote($id);
OK

2020-11-20 01:04 UTC, DerekCrannaford commented
Any suggested extensions/additions to unit test?

2020-11-25 00:09 UTC, adam-buckley approved these changes

2020-11-25 01:41 UTC, merged